# File: docker-compose.yml

version: "3.9"

services:
  finance-dashboard:
    build: .
    container_name: finance-dashboard
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: python run.py